### ISSUE TITLE
Tooltip doesn't show when point is behind area of another data set, showArea = true

### ISSUE THREAD

**Issue by TVerheggen** [Globegitter/chartist-plugin-tooltip#59]
Good afternoon, 

I created a fiddle to demonstrate how data points that are drawn "behind" the area (showArea = true) of another data set are not seen by the mouse hover.  

I tested it in Chrome & Safari, and I am using this version of the plugin "chartist-plugin-tooltip": "be609ef".

In the fiddle -  dataset: cashflow/orange line, point 2, has a value of 60, and is drawn behind the area of dataset: earnings/green.  The tooltip doesn't show on mouse-hover.  

https://jsfiddle.net/tcevans78/Lbs06fwq/1/

Thank you

**Comment by gionkunz** [comment]
Hi there, I saw a couple of "issues" in your Fiddle. The third argument to `Chartist.Svg` is the element class list, so there's no need to additionally set the `class` attribute within the attribute object on your circle element. Is there a reason why you're exchanging the line circles with those real circles? Usually you only need to do that if you want to use the stroke of the circles.

Your code actually added the `ct-area` class as well as your `my-cool-point` class to the circle elements. I've removed that so now the circles only have the later class.

Now you can use the `pointer-events` property to display the area and lines for any mouse events so that only the points are relevant to your mouse.

```css
.ct-area, .ct-line {
  pointer-events: none;
}
```

Check this forked fiddle: https://jsfiddle.net/nmqq1um3/

**Comment by TVerheggen** [comment]
Awesome!  This fixed it.  Thank you so much for your help.

Toshia



On Tue, Mar 8, 2016 at 12:30 PM, Gion Kunz <notifications@github.com> wrote:

> Hi there, I saw a couple of "issues" in your Fiddle. The third argument to
> Chartist.Svg is the element class list, so there's no need to
> additionally set the class attribute within the attribute object on your
> circle element. Is there a reason why you're exchanging the line circles
> with those real circles? Usually you only need to do that if you want to
> use the stroke of the circles.
>
> Your code actually added the ct-area class as well as your my-cool-point
> class to the circle elements. I've removed that so now the circles only
> have the later class.
>
> Now you can use the pointer-events property to display the area and lines
> for any mouse events so that only the points are relevant to your mouse.
>
> .ct-area, .ct-line {
>   pointer-events: none;
> }
>
> Check this forked fiddle: https://jsfiddle.net/nmqq1um3/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Globegitter/chartist-plugin-tooltip/issues/59#issuecomment-193903951>
> .
>



--
